name: triple_pokedex
description: Pokedex

publish_to: "none"

version: 1.0.0+1

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_triple: ^1.0.4
  mobx_triple: ^1.0.0
  mobx: ^2.0.0
  dio: ^4.0.0
  flutter_mobx: ^2.0.0
  flutter_modular: ^3.0.2+1
  flutter_svg: ^0.21.0-nullsafety.0
  google_fonts: ^2.0.0
  dartz: ^0.10.0-nullsafety.1
  flutter:
    sdk: flutter


dev_dependencies:
  mockito: ^5.0.3
  modular_codegen: ^3.0.0
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/types/
    - assets/loading.gif  
